name: Build on Push
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "17.x"
                  registry-url: "https://npm.pkg.github.com"
                  scope: "@redstonewizard08"
            - run: |
                  npm install
                  npm ci
                  npm run build:publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}